# Site Settings
title: Francisco Martinez Jr Website
email: martinezfran63@gmail.com
description: >
  A website about Francisco Martine Jr
baseurl:
url: "http://fmartinezjr.com"
twitter_username: martinezfran63
github_username:  martinezfran63
# Build Settings
sass:
  sass_dir: _sass
include: ['_pages']
kramdown:
  input: GFM