runtime: php55


handlers:

- url: /assets
  static_dir: assets
- url: /.*
  static_dir: _site/css
- url: /
  script: _site/default/index.html
- url: /contact
  script: _site/contact/index.html
- url: /career
  script: _site/career/index.html
- url: /interests
  script: _site/interests/index.html
- url: /portfolio
  script: _site/portfolio/index.html


